services:
  server:
    container_name: server
    image: nginx
    ports:
      - 8080:80
    networks:
      - backend
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    depends_on:
      app:
        condition: service_healthy
  app:
    container_name: app
    build:
      context: ./node
      dockerfile: ./Dockerfile
    networks:
      - backend
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://localhost:3000/healthcheck
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  db:
    container_name: db
    image: mysql:8.4
    command: --mysql-native-password=ON
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'node_db'
      MYSQL_ROOT_PASSWORD: 'Master.007,01'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'Master.007,01'
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 15s
    networks:
      - backend
networks:
  backend:
    driver: bridge